apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jjv4g9ujc-nodejs
  janus-idp.io/tekton: jjv4g9ujc-nodejs
  backstage.io/kubernetes-id: jjv4g9ujc-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jjv4g9ujc-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
