apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jjv4g9ujc-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jjv4g9ujc-nodejs 
  name: jjv4g9ujc-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jjv4g9ujc-nodejs 
